name: Deploy to Dev
on:
  push:
    branches:
      - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node-version: 16.13.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build app and deploy
        run: npm run deploy:dev
